//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TarjetaCredito()
        {
            this.MetodoPago = new HashSet<MetodoPago>();
        }
    
        public int TarjetaCreditoId { get; set; }
        public int NumeroTarjeta { get; set; }
        public string NombrePropietario { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
        public int CVV { get; set; }
        public Nullable<double> Monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MetodoPago> MetodoPago { get; set; }
    }
}
